# Generated by Django 5.0.4 on 2025-04-20 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0004_validationreference_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名前')),
            ],
            options={
                'db_table': 'docs_foreign_key',
            },
        ),
        migrations.CreateModel(
            name='DocsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='タイトル')),
                ('char_field', models.CharField(max_length=20, verbose_name='20文字まで')),
                ('text_field', models.TextField(verbose_name='テキスト')),
                ('integer_field', models.IntegerField(null=True, verbose_name='整数')),
                ('date_field', models.DateField(auto_now_add=True, verbose_name='日付')),
                ('date_time_field', models.DateTimeField(auto_now=True, verbose_name='日時')),
                ('choices', models.IntegerField(choices=[(0, 'alpha'), (1, 'bravo'), (2, 'charlie')], verbose_name='選択式')),
            ],
            options={
                'db_table': 'docs_main',
            },
        ),
        migrations.CreateModel(
            name='DocsManyToMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名前')),
            ],
            options={
                'db_table': 'docs_many_to_many',
            },
        ),
        migrations.AddConstraint(
            model_name='docsmain',
            constraint=models.UniqueConstraint(fields=('char_field', 'text_field'), name='unique_char_field_and_text_field'),
        ),
        migrations.AddConstraint(
            model_name='docsmain',
            constraint=models.CheckConstraint(check=models.Q(('integer_field__gte', 0)), name='integer_field_non_negative'),
        ),
        migrations.AddField(
            model_name='docsforeignkey',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_foreign_key', to='usage.docsmain', verbose_name='DocsMainへの参照'),
        ),
        migrations.AddField(
            model_name='docsmanytomany',
            name='ref',
            field=models.ManyToManyField(to='usage.docsmain'),
        ),
    ]
